version: "3.8"
   
services:
    web:
        container_name: core
        build: .
        restart: "always"
        env_file: .env
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - "postgres"
            - "redis"
            - "selenium"


    selenium:
        image: selenium/standalone-chrome
        container_name: selenium
        environment:
            - SCREEN_WIDTH=1366
            - SCREEN_HEIGHT=768
        ports:
            - "4444:4444"


    celery_beat:
        restart: always
        build:
            context: .
        command: celery -A core beat -l INFO
        volumes:
            - .:/django
        container_name: celery_beat_con
        depends_on:
            - postgres
            - redis
            - web
        env_file: .env


    celery_worker:
        restart: always
        build:
            context: .
        command: celery -A core worker -l INFO
        container_name: celery_worker_con
        depends_on:
            - postgres
            - redis
            - web


    postgres:
        image: postgres:13.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file: .env
        environment:
            - LC_ALL=C.UTF-8
    redis:
        image: redis:6-alpine
        
volumes:
    postgres_data:

