# Generated by Django 3.2 on 2023-04-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='refresh_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
