# Generated by Django 3.2 on 2023-04-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_instagram_refresh_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='followers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='following',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
